name: master
on:
  push:
    branches:
      - master
jobs:
  ci:
    uses: ThreeDotsLabs/watermill/.github/workflows/tests.yml@master
    with:
      stress-tests: true
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
