name: master
on:
  push:
    branches:
      - master
jobs:
  ci:
    uses: ThreeDotsLabs/watermill/.github/workflows/tests.yml@master
    with:
      stress-tests: true
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: test_codecov
    - uses: codecov/codecov-action@v3
